### ISSUE TITLE
Make obj_io.h C++11 compatible, or remove the "cpp11" tag from the project

### ISSUE THREAD

**Issue by Kowbell** [thinks/obj-io#5]
`obj_io.h` uses anonymous lambdas, which is supported by C++14 but not C++11. If you try to use this header with `-std=c++11`, you'll get errors like this:

```
obj_io.h:726:48: error: 'auto' not allowed in lambda parameter
                                      [](const auto&) {},  // No validation.
                                               ^~~~
obj_io.h:735:16: error: 'auto' not allowed in lambda parameter
      [](const auto& tex_coord) { ValidateObjTexCoord(tex_coord); }, newline);
               ^~~~
obj_io.h:750:46: error: 'auto' not allowed in lambda parameter
                                    [](const auto&) {},  // No validation.
                                             ^~~~
obj_io.h:766:16: error: 'auto' not allowed in lambda parameter
      [](const auto& face) {
```

Thanks to the author for putting this out there, and it looks like this project is dead anyway so I don't expect a fix, but in case anybody found this online and is checking the Issues page first: it is _not_ C++11.

**Comment by thinks** [comment]
Thanks for pointing this out, you are correct of course. Had I set up proper CI testing I would have caught this. But I didn't, and as you note this project is quite dead (if it was ever really alive?). I'm just going to remove the **cpp11** tag and hope for the best.
